import { RegexRule } from '../types';

export const DEFAULT_RULES: RegexRule[] = [
  {
    id: 'sec-aws-akid',
    name: 'AWS Access Key ID',
    pattern: '\\b(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}\\b',
    flags: 'g',
    category: 'CLOUD_CREDENTIAL',
    severity: 'CRITICAL',
    description: 'Chave de acesso pública da AWS encontrada hardcoded no código.',
    remediation: 'Utilize AWS IAM Roles, variáveis de ambiente (AWS_ACCESS_KEY_ID) ou AWS Secrets Manager.',
    minEntropy: 3.5,
    enabled: true,
    tags: ['aws', 'cloud', 'iam'],
    exampleMatch: 'AKIA' + '****************'
  },
  {
    id: 'sec-aws-secret',
    name: 'AWS Secret Access Key',
    pattern: '(?:aws_secret_access_key|aws_secret|aws_key)\\s*[:=]\\s*[\'"][A-Za-z0-9/+=]{40}[\'"]',
    flags: 'gi',
    category: 'CLOUD_CREDENTIAL',
    severity: 'CRITICAL',
    description: 'Segredo de autenticação da AWS exposto diretamente.',
    remediation: 'Rotacione a chave imediatamente no console da AWS e migre para credenciais temporárias do STS.',
    minEntropy: 4.2,
    enabled: true,
    tags: ['aws', 'secrets', 'critical'],
    exampleMatch: 'aws_secret_access_key="****************************************"'
  },
  {
    id: 'sec-google-api',
    name: 'Google Cloud / Gemini API Key',
    pattern: '\\bAIza[0-9A-Za-z\\-_]{35}\\b',
    flags: 'g',
    category: 'API_KEY',
    severity: 'HIGH',
    description: 'Chave de API do Google Cloud ou Google Gemini exposta no código cliente.',
    remediation: 'Restrinja a chave por HTTP referrers e IPs no Google Cloud Console ou crie rotas proxy server-side (/api/*).',
    minEntropy: 4.0,
    enabled: true,
    tags: ['google', 'gemini', 'gcp'],
    exampleMatch: 'AIzaSy' + '***********************************'
  },
  {
    id: 'sec-github-pat',
    name: 'GitHub Personal Access Token',
    pattern: '\\b(?:ghp_[0-9a-zA-Z]{36}|gho_[0-9a-zA-Z]{36}|github_pat_[0-9a-zA-Z_]{82})\\b',
    flags: 'g',
    category: 'AUTH_TOKEN',
    severity: 'CRITICAL',
    description: 'Token de Acesso Pessoal do GitHub exposto no repositório.',
    remediation: 'Revogue o token imediatamente em GitHub > Settings > Developer Settings e armazene como GitHub Secret.',
    minEntropy: 4.1,
    enabled: true,
    tags: ['github', 'vcs', 'ci-cd'],
    exampleMatch: 'ghp_' + '************************************'
  },
  {
    id: 'sec-stripe-secret',
    name: 'Stripe Secret API Key',
    pattern: '\\b(?:sk|rk)_(?:live|test)_[0-9a-zA-Z]{24,99}\\b',
    flags: 'g',
    category: 'API_KEY',
    severity: 'CRITICAL',
    description: 'Chave secreta ou restrita do Stripe exposta. Permite execução de cobranças e transferências financeiras.',
    remediation: 'Rotacione a chave no painel do Stripe e nunca envie chaves secretas para o bundle frontend do navegador.',
    minEntropy: 4.0,
    enabled: true,
    tags: ['stripe', 'payments', 'pci-dss'],
    exampleMatch: 'sk_live_' + '****************************************'
  },
  {
    id: 'sec-jwt-token',
    name: 'JSON Web Token (JWT)',
    pattern: '\\beyJ[A-Za-z0-9-_=]+\\.[A-Za-z0-9-_=]+\\.[A-Za-z0-9-_.+/=]*\\b',
    flags: 'g',
    category: 'AUTH_TOKEN',
    severity: 'HIGH',
    description: 'Token JWT estático embutido no código-fonte.',
    remediation: 'Substitua tokens estáticos por fluxos dinâmicos de autenticação via OAuth2 / OIDC.',
    minEntropy: 4.3,
    enabled: true,
    tags: ['jwt', 'auth', 'tokens'],
    exampleMatch: 'eyJhbGciOi...' + '.[PAYLOAD]...' + '.[SIGNATURE]...'
  },
  {
    id: 'sec-slack-webhook',
    name: 'Slack Incoming Webhook / Bot Token',
    pattern: 'https://hooks\\.slack\\.com/services/T[a-zA-Z0-9_]{8}/B[a-zA-Z0-9_]{8,12}/[a-zA-Z0-9_]{24}|xox[baprs]-[0-9]{10,13}-[0-9]{10,13}[a-zA-Z0-9-]*',
    flags: 'g',
    category: 'AUTH_TOKEN',
    severity: 'HIGH',
    description: 'URL de webhook do Slack ou token de bot hardcoded.',
    remediation: 'Configure a URL do webhook como variável de ambiente protegida no servidor.',
    minEntropy: 3.8,
    enabled: true,
    tags: ['slack', 'webhooks', 'notifications'],
    exampleMatch: ['https:', '', ['hooks', 'slack', 'com'].join('.'), 'services', 'T00000000', 'B00000000', 'X'.repeat(24)].join('/')
  },
  {
    id: 'sec-private-key',
    name: 'RSA / OpenSSH Private Key',
    pattern: '-----BEGIN (?:RSA|EC|OPENSSH|DSA|PGP|PRIVATE) KEY-----[\\s\\S]*?-----END (?:RSA|EC|OPENSSH|DSA|PGP|PRIVATE) KEY-----',
    flags: 'g',
    category: 'PRIVATE_KEY',
    severity: 'CRITICAL',
    description: 'Chave criptográfica privada encontrada embutida no arquivo.',
    remediation: 'Remova chaves privadas do controle de versão e configure-as através do SSH Agent ou Cofre de Chaves.',
    enabled: true,
    tags: ['crypto', 'ssh', 'pki'],
    exampleMatch: '-----' + 'BEGIN [RSA] PRIVATE KEY' + '-----\n[CONTEUDO_DA_CHAVE_PRIVADA_REMOVIDO]\n-----' + 'END [RSA] PRIVATE KEY' + '-----'
  },
  {
    id: 'sec-db-uri',
    name: 'Database Connection URI with Credentials',
    pattern: '(?:mongodb(?:\\+srv)?|postgres(?:ql)?|mysql|redis):\\/\\/[^\\s:"\']+:[^\\s:"\']+@[^\\s:"\']+',
    flags: 'gi',
    category: 'DATABASE_URI',
    severity: 'CRITICAL',
    description: 'String de conexão a banco de dados contendo usuário e senha em texto claro.',
    remediation: 'Extraia as credenciais para DATABASE_URL em .env e utilize poolers com autenticação IAM quando disponível.',
    enabled: true,
    tags: ['database', 'postgres', 'mongo', 'mysql'],
    exampleMatch: 'postgres://usuario:SENHA_SECRETA_AQUI@db.prod.internal:5432/main'
  },
  {
    id: 'sec-hardcoded-pass',
    name: 'Hardcoded Password Assignment',
    pattern: '(?:password|passwd|pwd|db_pass|secret_key|client_secret)\\s*[:=]\\s*[\'"][^\'"]{8,64}[\'"]',
    flags: 'gi',
    category: 'PASSWORD',
    severity: 'HIGH',
    description: 'Atribuição de senha ou chave secreta fixa no código JavaScript.',
    remediation: 'Nunca armazene senhas no código-fonte. Utilize injeção em tempo de execução via variáveis de ambiente.',
    minEntropy: 3.2,
    enabled: true,
    tags: ['password', 'credentials'],
    exampleMatch: 'const db_pass = "<SENHA_PADRAO_EXEMPLO>";'
  },
  {
    id: 'sec-openai-key',
    name: 'OpenAI API Secret Key',
    pattern: '\\bsk-(?:proj-|live-)?[a-zA-Z0-9_-]{32,80}\\b',
    flags: 'g',
    category: 'API_KEY',
    severity: 'CRITICAL',
    description: 'Chave secreta de API da OpenAI encontrada no código.',
    remediation: 'Revogue a chave no painel da OpenAI e proteja em backend proxy.',
    minEntropy: 4.1,
    enabled: true,
    tags: ['openai', 'ai', 'api-key'],
    exampleMatch: 'sk-proj-' + '<CHAVE_OPENAI_DEMO_REMOVIDA>'
  },
  {
    id: 'sec-sendgrid-key',
    name: 'SendGrid API Key',
    pattern: '\\bSG\\.[0-9A-Za-z-_]{22}\\.[0-9A-Za-z-_]{43}\\b',
    flags: 'g',
    category: 'API_KEY',
    severity: 'HIGH',
    description: 'Chave de envio de e-mails do SendGrid exposta.',
    remediation: 'Rotacione a chave na SendGrid e transfira para variáveis de ambiente do backend.',
    minEntropy: 4.0,
    enabled: true,
    tags: ['sendgrid', 'email'],
    exampleMatch: 'SG.' + '1234567890123456789012.' + '1234567890123456789012345678901234567890123'
  },
  {
    id: 'sec-sensitive-api-path',
    name: 'Sensitive or Admin API Route',
    pattern: '[\'"](?:\\/api\\/v[0-9]+)?\\/(?:admin|internal|superadmin|debug|actuator|metrics|management|auth\\/token|users\\/export|billing\\/charge)[^\\s\'"]*[\'"]',
    flags: 'gi',
    category: 'API_PATH',
    severity: 'MEDIUM',
    description: 'Caminho de rota de API sensível ou administrativa mapeada diretamente no frontend.',
    remediation: 'Garanta controle de acesso rigoroso (RBAC) e proteja rotas de administração para que não sejam expostas em bundles públicos.',
    enabled: true,
    tags: ['api-path', 'admin', 'endpoints'],
    exampleMatch: '"/api/v1/admin/users/export"'
  },
  {
    id: 'sec-api-endpoint',
    name: 'Hardcoded API Path / Endpoint',
    pattern: '[\'"](?:https?:\\/\\/[a-zA-Z0-9.-]+)?\\/(?:api|v1|v2|graphql|rest|webhook)\\/[a-zA-Z0-9_\\-\\.\\/]+[\'"]',
    flags: 'gi',
    category: 'API_PATH',
    severity: 'LOW',
    description: 'Endpoint ou caminho de API fixo no código.',
    remediation: 'Utilize URLs base configuráveis via variáveis de ambiente (ex: process.env.API_BASE_URL).',
    enabled: true,
    tags: ['api-path', 'endpoints', 'rest'],
    exampleMatch: '"https://api.empresa.com.br/v1/payments"'
  }
];
